name: workspace

environment:
  sdk: ^3.9.0

workspace:
  - app

  - packages/core/design
  - packages/core/network
  - packages/core/router
  
  - packages/features/home

dev_dependencies:
  melos: ^7.1.1
  injectable_generator: 
  build_runner: 

melos:
  scripts:
    generate:
      run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build