name: workspace

environment:
  sdk: ^3.9.0

workspace:
  - app

  - packages/core/design
  - packages/core/network
  - packages/core/router
  - packages/core/storage
  
  - packages/features/home
  - packages/features/create
  - packages/features/history

dev_dependencies:
  melos: ^7.1.1
  injectable_generator: 
  build_runner: 

melos:
  scripts:
    generate:
      description: Generate code for all workspace packages
      run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build
    test:
      description: Run tests for all workspace packages
      run: |
        melos exec -c 1 --dir-exists=test --flutter -- flutter test