name: app
description: "A url shortner"

resolution: workspace
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  get_it: 
  injectable: 

  router:
    path: ../packages/core/router
  storage:
    path: ../packages/core/storage
  network:
    path: ../packages/core/network

  home:
    path: ../packages/features/home
  create:
    path: ../packages/features/create
  history:
    path: ../packages/features/history

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: 
  build_runner: 

  flutter_lints:
  
flutter:
  uses-material-design: true