name: network
description: "A new Flutter package project."
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio:
  get_it: 
  injectable: 
  go_router: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: 
  build_runner: 
  mockito:

  flutter_lints: