name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Flutter Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Dart & Flutter Versions
        run: |
          dart --version
          flutter --version

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap workspace
        run: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          melos bootstrap

      - name: Generate code (build_runner)
        run: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          melos run generate

      - name: Run tests with coverage per package
        run: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          melos run test_coverage

      - name: List coverage files
        run: |
          echo "Workspace root: $(pwd)"
          ls -la
          echo "\nFound coverage files:"
          find . -type f -name lcov.info -print
          
      - name: create code coverage report
        uses: im-open/code-coverage-report-generator@4.9.0
        with:
          reports: '*/**/lcov.info'
          title: jest code coverage

      - name: create status check/comment for code coverage results
        id: jest_coverage_check
        uses: im-open/process-code-coverage-summary@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          create-pr-comment: true
          update-comment-if-one-exists: true
          update-comment-key: 'jest'